name: my_pet_care
description: MY PET CARE - Booking stile per servizi pet (Flutter + Firebase)
publish_to: "none"
version: 1.0.0+100

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  uni_links: ^0.5.1
  http: ^1.5.0
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.4
  flutter_stripe: ^11.2.0
  webview_flutter: ^4.13.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf